### ISSUE TITLE
ModuleNotFoundError: No module named 'apex.contrib'

### ISSUE THREAD

**Issue by manjunaths** [mlperf/training_results_v0.6#2]
When I run the translation benchmark I am getting the below error. I modified the Dockerfile to install the latest apex, but that didn't fix the problem. Any ideas what might be wrong ?

```Traceback (most recent call last):
  File "train.py", line 768, in <module>
    distributed_main(args)
  File "/workspace/translation/distributed_train.py", line 40, in main
    single_process_main(args)
  File "/workspace/translation/train.py", line 96, in main
    criterion = task.build_criterion(args)
  File "/workspace/translation/fairseq/tasks/fairseq_task.py", line 46, in build_criterion
    return criterions.build_criterion(args, self)
  File "/workspace/translation/fairseq/criterions/__init__.py", line 19, in build_criterion
    return CRITERION_REGISTRY[args.criterion](args, task)
  File "/workspace/translation/fairseq/criterions/label_smoothed_cross_entropy.py", line 21, in __init__
    from apex.contrib.xentropy import SoftmaxCrossEntropyLoss
ModuleNotFoundError: No module named 'apex.contrib'
```

**Comment by manjunaths** [comment]
Found a solution to the problem. If anyone is still facing the same problem, then adding this line to the Dockerfile and rebuilding the image should fix the problem.

```
RUN git clone https://github.com/NVIDIA/apex && cd apex && git checkout integrate_label_smoothing && pip install -v --no-cache-dir --global-option="--xentropy"  --global-option="--cpp_ext" --global-option="--cuda_ext" ./
```
